Remove commands library for Python 3
prakashdanish/vim-zen pull request #12
Opened 2018-09-24 13:50 UTC by chris-pauley

The commands library has been removed in Python 3 ([see the docs](https://docs.python.org/2/library/commands.html)). For the sake of consistent behavior, I have replaced the call to the commands library with the [code called by the commands library](https://github.com/enthought/Python-2.7.3/blob/master/Lib/commands.py#L56).

2018-10-03 05:33 UTC, danishprakash commented
@chris-pauley thanks a lot for this PR. But isn't this the same as using the `os.commands`. I'm not sure if you've read about this or not, but it is commonly advised to use the `subprocess` module to execute system commands from within python. Could you update this PR to use the `subprocess` module if you have the time and resources?

2018-10-03 05:34 UTC, danishprakash requested changes
@chris-pauley thanks a lot for this PR. But isn't this the same as using the `os.commands`. I'm not sure if you've read about this or not, but it is commonly advised to use the `subprocess` module to execute system commands from within python. Could you update this PR to use the `subprocess` module if you have the time and resources?

2018-10-03 11:54 UTC, chris-pauley commented
Hey danish, will see if I can switch it over at some point. If you check out the code that I liked above, the commands library actually was calling those os commands directly. I agree using a subprocess is a better implentation

2018-10-09 05:02 UTC, danishprakash commented
>  If you check out the code that I liked above, the commands library actually was calling those os commands directly.

You're right but, correct me If I'm wrong here, isn't this similar to using the `os` module? Anyway, as you said, It'd make much more sense If we jump over to `subprocess` for this.

2022-07-07 15:55 UTC, closed without merging